In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Aivle_빅프/donateacry_corpus/exp1_testing.csv')
print(data.shape)
data.tail()

(457, 39042)


Unnamed: 0             0             1             2             3  \
452         452  4.289608e-18  1.867446e-16  6.420816e-15  2.227083e-15   
453         453  6.524383e-12  9.780674e-12  9.848814e-11  3.771047e-12   
454         454  9.174426e-12  1.503270e-12  1.717807e-10  2.135950e-11   
455         455  5.628047e-19  5.471258e-22  3.214885e-22  4.835827e-12   
456         456  1.168783e-26  9.895399e-27  5.581826e-27  6.448266e-22   

                4             5             6             7             8  \
452  8.054947e-17  2.123049e-14  1.836394e-14  2.825232e-15  4.707069e-16   
453  9.803543e-12  3.381772e-11  1.511806e-11  2.343704e-11  2.759917e-10   
454  1.130944e-11  2.979750e-11  1.295525e-10  3.544029e-11  3.886444e-10   
455  4.759479e-16  7.117379e-15  1.428444e-13  7.721411e-12  1.419541e-11   
456  1.553599e-28  1.817216e-18  2.963649e-17  1.143936e-16  1.516958e-15   

     ...  39031  39032  39033  39034  39035  39036  39037  39038  39039  label  
452  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  tired  
453  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  tired  
454  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  tired  
455  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  tired  
456  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  tired  

[5 rows x 39042 columns]

# 실험 1 : 원본 데이터 사용
- 데이터 불균형 유지되어있음
- 대부분의 machine leaning 모델에서 hungry(최빈 클래스)만 맞춤

In [ ]:
from sklearn.model_selection import train_test_split


y = data.iloc[:,-1]
X = data.drop(columns = 'label')
X = X.astype(np.float32)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)


print(X_train.shape, y_train.shape)
print(X_test.shape, y_train.shape)

(319, 39041) (319,)
(138, 39041) (319,)


In [ ]:
#Code to hide deprication warnings

from IPython.display import HTML
HTML('''<script>
code_show_err=false;
function code_toggle_err() {
 if (code_show_err){
 $('div.output_stderr').hide();
 } else {
 $('div.output_stderr').show();
 }
 code_show_err = !code_show_err
}
$( document ).ready(code_toggle_err);
</script>
To toggle on/off output_stderr, click <a href="javascript:code_toggle_err()">here</a>.''')

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, precision_score, recall_score

def get_scores(classifier, X_train, X_test, y_train, y_test, **kwargs):
    model = classifier(**kwargs)
    model.fit(X_train, y_train)
    y_predict = model.predict(X_test)
    conf_matrix = confusion_matrix(y_test, y_predict)
    return model.score(X_test, y_test), \
           precision_score(y_test, y_predict, average='weighted'), \
           recall_score(y_test, y_predict, average='weighted'), \
           conf_matrix

print("    Model, Accuracy, Precision, Recall, Confusion Matrix")
accuracy, precision, recall, conf_matrix = get_scores(RandomForestClassifier, X_train, X_test, y_train, y_test, n_estimators=25, max_features=5)
print("    Random Forest:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

accuracy, precision, recall, conf_matrix = get_scores(LogisticRegression, X_train, X_test, y_train, y_test)
print("    Logistic Regression:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

accuracy, precision, recall, conf_matrix = get_scores(DecisionTreeClassifier, X_train, X_test, y_train, y_test)
print("    Decision Tree:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

accuracy, precision, recall, conf_matrix = get_scores(SVC, X_train, X_test, y_train, y_test)
print("    SVM:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

# accuracy, precision, recall, conf_matrix = get_scores(MultinomialNB, X_train, X_test, y_train, y_test)
# print("    Naive Bayes:", accuracy, precision, recall)
# print("    Confusion Matrix:\n", conf_matrix)


    Model, Accuracy, Precision, Recall, Confusion Matrix


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


    Random Forest: 0.8333333333333334 0.6944444444444445 0.8333333333333334
    Confusion Matrix:
 [[  0   0   0   5   0]
 [  0   0   0   3   0]
 [  0   0   0   8   0]
 [  0   0   0 115   0]
 [  0   0   0   7   0]]


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


    Logistic Regression: 0.7318840579710145 0.7272438342232392 0.7318840579710145
    Confusion Matrix:
 [[ 0  1  0  4  0]
 [ 1  0  0  2  0]
 [ 1  0  3  4  0]
 [ 0  4 12 98  1]
 [ 0  0  1  6  0]]
    Decision Tree: 0.9710144927536232 0.9698692320506412 0.9710144927536232
    Confusion Matrix:
 [[  4   1   0   0   0]
 [  2   1   0   0   0]
 [  0   0   7   1   0]
 [  0   0   0 115   0]
 [  0   0   0   0   7]]
    SVM: 0.8333333333333334 0.6944444444444445 0.8333333333333334
    Confusion Matrix:
 [[  0   0   0   5   0]
 [  0   0   0   3   0]
 [  0   0   0   8   0]
 [  0   0   0 115   0]
 [  0   0   0   7   0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# 실험 2 : hungry 데이터 비율을 줄이기
- 데이터 불균형은 해결됨
- 데이터 정보 부족으로 제대로된 분류가 되지 않음

In [ ]:
data['label'].value_counts()

label
hungry        382
discomfort     27
tired          24
belly_pain     16
burping         8
Name: count, dtype: int64

In [ ]:
hungry_data = data[data['label'] == 'hungry']
hungry_data = hungry_data.head(27)

filterd_data = pd.concat([hungry_data, data[data['label'] != 'hungry']])
print(filterd_data.shape)
filterd_data.head()

(102, 39042)


Unnamed: 0             0             1             2             3  \
51          51  1.168783e-26  9.895399e-27  5.581826e-27  6.448295e-22   
52          52  1.168783e-26  9.895399e-27  5.581826e-27  6.448295e-22   
53          53  1.163078e-26  3.631320e-16  8.968976e-17  6.665843e-16   
54          54  1.168783e-26  9.895399e-27  5.581826e-27  6.448295e-22   
55          55  3.943032e-12  4.539119e-12  2.316500e-11  7.262338e-11   

               4             5             6             7             8  ...  \
51  1.466376e-28  1.900255e-32  2.118744e-33  1.186738e-35  2.386806e-42  ...   
52  1.466376e-28  1.900255e-32  2.118744e-33  1.186738e-35  2.386806e-42  ...   
53  7.533582e-17  2.830787e-15  1.592550e-15  3.766136e-16  1.813308e-13  ...   
54  1.466376e-28  1.900255e-32  2.118744e-33  1.186738e-35  2.386806e-42  ...   
55  4.860308e-10  5.359333e-12  4.462452e-10  2.630336e-10  3.436842e-10  ...   

           39031         39032         39033         39034         39035  \
51  2.944189e-15  7.008582e-16  1.115383e-16  5.146143e-17  1.120200e-16   
52  1.458172e-13  1.447071e-13  9.190454e-14  1.083983e-13  1.470866e-13   
53  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
54  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
55  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   

           39036         39037     39038     39039   label  
51  7.081642e-16  2.659310e-15  0.000012  0.000055  hungry  
52  1.187365e-13  1.143976e-13  0.004987  0.023249  hungry  
53  0.000000e+00  0.000000e+00  0.000000  0.000000  hungry  
54  0.000000e+00  0.000000e+00  0.000000  0.000000  hungry  
55  0.000000e+00  0.000000e+00  0.000000  0.000000  hungry  

[5 rows x 39042 columns]

In [ ]:
filterd_data['label'].value_counts()

label
hungry        27
discomfort    27
tired         24
belly_pain    16
burping        8
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split


y = filterd_data.iloc[:,-1]
X = filterd_data.drop(columns = 'label')
X = X.astype(np.float32)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)


print(X_train.shape, y_train.shape)
print(X_test.shape, y_train.shape)

(71, 39041) (71,)
(31, 39041) (71,)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, precision_score, recall_score

def get_scores(classifier, X_train, X_test, y_train, y_test, **kwargs):
    model = classifier(**kwargs)
    model.fit(X_train, y_train)
    y_predict = model.predict(X_test)
    conf_matrix = confusion_matrix(y_test, y_predict)
    return model.score(X_test, y_test), \
           precision_score(y_test, y_predict, average='weighted'), \
           recall_score(y_test, y_predict, average='weighted'), \
           conf_matrix

print("    Model, Accuracy, Precision, Recall, Confusion Matrix")
accuracy, precision, recall, conf_matrix = get_scores(RandomForestClassifier, X_train, X_test, y_train, y_test, n_estimators=25, max_features=5)
print("    Random Forest:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

accuracy, precision, recall, conf_matrix = get_scores(LogisticRegression, X_train, X_test, y_train, y_test)
print("    Logistic Regression:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

accuracy, precision, recall, conf_matrix = get_scores(DecisionTreeClassifier, X_train, X_test, y_train, y_test)
print("    Decision Tree:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

accuracy, precision, recall, conf_matrix = get_scores(SVC, X_train, X_test, y_train, y_test)
print("    SVM:", accuracy, precision, recall)
print("    Confusion Matrix:\n", conf_matrix)

# accuracy, precision, recall, conf_matrix = get_scores(MultinomialNB, X_train, X_test, y_train, y_test)
# print("    Naive Bayes:", accuracy, precision, recall)
# print("    Confusion Matrix:\n", conf_matrix)


    Model, Accuracy, Precision, Recall, Confusion Matrix
    Random Forest: 0.3225806451612903 0.30107526881720426 0.3225806451612903
    Confusion Matrix:
 [[1 0 0 1 3]
 [1 0 1 0 1]
 [1 1 3 2 1]
 [0 0 4 3 1]
 [2 0 0 2 3]]


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


    Logistic Regression: 0.1935483870967742 0.17866103430619557 0.1935483870967742
    Confusion Matrix:
 [[0 2 1 0 2]
 [1 1 0 0 1]
 [0 1 2 2 3]
 [1 1 3 2 1]
 [0 0 1 5 1]]
    Decision Tree: 0.8064516129032258 0.818100358422939 0.8064516129032258
    Confusion Matrix:
 [[2 3 0 0 0]
 [2 1 0 0 0]
 [0 0 7 1 0]
 [0 0 0 8 0]
 [0 0 0 0 7]]
    SVM: 0.3225806451612903 0.2604540023894863 0.3225806451612903
    Confusion Matrix:
 [[0 0 5 0 0]
 [0 0 3 0 0]
 [0 0 7 1 0]
 [0 0 5 3 0]
 [0 0 7 0 0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


# 모델 저장

In [ ]:
import cPickle

def pickle_model(model, modelname):
    with open('models/' + str(modelname) + '.pkl', 'wb') as f:
        return cPickle.dump(model, f)

model = RandomForestClassifier()
model.fit(X,y)
pickle_model(model, "myRandomForest")

In [ ]:
def getModel(pickle_path):
    with open(pickle_path, 'rb') as f:
        return cPickle.load(f)

In [ ]:
model = getModel("models/myRandomForest.pkl")